### ISSUE TITLE
感谢作者，了解一下是否有后续计划？

### ISSUE THREAD

**Issue by codinglist** [KingBes/php-webui-composer#2]
非常感谢作者，webui官方文档php示例代码部分展示“// In development...”，了解一下是项目有后续计划在完善中吗？

**Comment by KingBes** [comment]
官方文档会在后续完善
你也可以暂时在[中文自述](https://github.com/KingBes/php-webui-composer/blob/main/README-zh-CN.md)中查看 函数说明

**Comment by codinglist** [comment]
感谢回复
